export const GET_TABS_CONTENT_STARTED = "GET_TABS_CONTENT_STARTED";
export const GET_TABS_CONTENT_SUCCESS = "GET_TABS_CONTENT_SUCCESS";
export const GET_TABS_CONTENT_FAILURE = "GET_TABS_CONTENT_FAILURE";
export const GET_TABS_STARTED = "GET_TABS_STARTED";
export const GET_TABS_SUCCESS = "GET_TABS_SUCCESS";
export const GET_TABS_FAILURE = "GET_TABS_FAILURE";
export const UPDATE_ACTIVE_FONT = "UPDATE_ACTIVE_FONT";
